name: Microservices Docker CI/CD Pipeline

# Kích hoạt khi có push lên branch chính
on:
  push:
    branches:
      - main
  workflow_dispatch: # Cho phép chạy thủ công

# Định nghĩa các biến môi trường chung
env:
  # LƯU Ý: Đặt tên đăng nhập trực tiếp (nếu tên này không chứa thông tin nhạy cảm)
  # Tuy nhiên, cách an toàn nhất là sử dụng Secret cho cả hai.
  DOCKER_USERNAME: haidang04 
  
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # -----------------------------------------------------
      # BƯỚC 1: LOG IN VÀO DOCKER HUB (Sửa lại cách sử dụng Secret)
      # -----------------------------------------------------
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          # Sử dụng biến môi trường DOCKER_USERNAME đã định nghĩa ở trên
          username: ${{ env.DOCKER_USERNAME }}
          # Sử dụng Secret DOCKER_PASSWORD đã lưu trữ trong GitHub
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      # -----------------------------------------------------
      # BƯỚC 2: XỬ LÝ DỊCH VỤ AUTH
      # -----------------------------------------------------
      - name: Build and Push 'Auth' Service
        uses: docker/build-push-action@v5
        with:
          context: ./auth 
          push: true
          tags: |
            ${{ env.DOCKER_USERNAME }}/e-project-auth:latest
            ${{ env.DOCKER_USERNAME }}/e-project-auth:${{ github.sha }}

      # -----------------------------------------------------
      # BƯỚC 3: XỬ LÝ DỊCH VỤ PRODUCT
      # -----------------------------------------------------
      - name: Build and Push 'Product' Service
        uses: docker/build-push-action@v5
        with:
          context: ./product 
          push: true
          tags: |
            ${{ env.DOCKER_USERNAME }}/e-project-product:latest
            ${{ env.DOCKER_USERNAME }}/e-project-product:${{ github.sha }}

      # -----------------------------------------------------
      # BƯỚC 4: XỬ LÝ DỊCH VỤ ORDER
      # -----------------------------------------------------
      - name: Build and Push 'Order' Service
        uses: docker/build-push-action@v5
        with:
          context: ./order 
          push: true
          tags: |
            ${{ env.DOCKER_USERNAME }}/e-project-order:latest
            ${{ env.DOCKER_USERNAME }}/e-project-order:${{ github.sha }}

      # -----------------------------------------------------
      # BƯỚC 5: XỬ LÝ DỊCH VỤ API GATEWAY
      # -----------------------------------------------------
      - name: Build and Push 'API Gateway' Service
        uses: docker/build-push-action@v5
        with:
          context: ./api-gateway # Context trỏ đến thư mục API Gateway
          push: true
          tags: |
            ${{ env.DOCKER_USERNAME }}/e-project-gateway:latest
            ${{ env.DOCKER_USERNAME }}/e-project-gateway:${{ github.sha }}
